//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMapTestRust.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class RunHistory : global::System.Configuration.ApplicationSettingsBase {
        
        private static RunHistory defaultInstance = ((RunHistory)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RunHistory())));
        
        public static RunHistory Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection HistoryList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["HistoryList"]));
            }
            set {
                this["HistoryList"] = value;
            }
        }
    }
}
